DROP TABLE IF EXISTS PARTIDA;
DROP TABLE IF EXISTS PARTICIPACAO;
DROP TABLE IF EXISTS TIME;
DROP TABLE IF EXISTS GINASIO;
DROP TABLE IF EXISTS JOGADOR;
DROP TABLE IF EXISTS ARBITRO;
DROP TABLE IF EXISTS ESPORTE;
DROP TABLE IF EXISTS UNIVERSIDADE;
