DROP TABLE IF EXISTS ARBITRO CASCADE;
DROP TABLE IF EXISTS ESPORTE CASCADE;
DROP TABLE IF EXISTS UNIVERSIDADE CASCADE;
DROP TABLE IF EXISTS TIME CASCADE;
DROP TABLE IF EXISTS GINASIO CASCADE;
DROP TABLE IF EXISTS PARTIDA CASCADE;
DROP TABLE IF EXISTS PARTICIPACAO CASCADE;
DROP TABLE IF EXISTS JOGADOR CASCADE;







