--Q1
SELECT DATA, LOCAL FROM PARTIDA WHERE LOCAL = 'SANTOS'
--01/02/18	SANTOS

--Q2
SELECT NOME, SALDO_GOLS FROM TIME 
WHERE TIPO = 'AMADOR' AND ESTADO = 'SP';
--INTER	1

--Q3
SELECT TO_CHAR(DATA), LOCAL FROM PARTIDA 
WHERE TIME1 = 'PALMEIRAS' OR TIME2 = 'PALMEIRAS'
-- 02/03/18	(NULL)
-- 01/02/18	SANTOS
SELECT DATA, LOCAL FROM PARTIDA 
WHERE TIME1 = 'PALMEIRAS' OR TIME2 = 'PALMEIRAS'
-- 02/03/18	(NULL)
-- 01/02/18	SANTOS

--Q4
SELECT J.CPF, J.NOME, J.DATA_NASC, T.NOME, T.ESTADO FROM
JOGADOR J
JOIN TIME T
ON T.NOME = J.TIME;
--400.560.298-60	JOSE	12/10/97	PALMEIRAS	SP

SELECT * FROM JOGADOR CROSS JOIN TIME;

SELECT * FROM JOGADOR J
INNER JOIN TIME T ON J.TIME = T.NOME;


--Q5
SELECT CPF, NOME, DATA_NASC FROM JOGADOR
WHERE TIME IN (SELECT NOME FROM TIME WHERE ESTADO = 'SP')
-- 400.560.298-61	REINALDO	02/09/95
-- 400.560.298-60	JOSE		12/10/97
-- 103.460.333-60	EDERSON		10/10/89
-- 301.400.298-00	ALESSANDRO	01/03/92

SELECT J.CPF, J.NOME, J.DATA_NASC FROM JOGADOR J
JOIN TIME T
ON T.NOME = J.TIME
WHERE T.ESTADO = 'SP';
-- 400.560.298-61	REINALDO	02/09/95
-- 400.560.298-60	JOSE		12/10/97
-- 103.460.333-60	EDERSON		10/10/89
-- 301.400.298-00	ALESSANDRO	01/03/92

--Q6
SELECT COR_PRINCIPAL, TIME FROM UNIFORME U
JOIN TIME T ON T.NOME = U.TIME
WHERE U.TIPO = 'TITULAR'
AND T.ESTADO = 'MG'
AND T.TIPO = 'PROFISSIONAL';
--AZUL	CRUZEIRO

--Q7
SELECT 
    J.NOME, 
    J.NATURALIDADE, 
    T.NOME, 
    T.ESTADO, 
    P.POSICAO 
FROM
    JOGADOR J
JOIN TIME T
ON T.NOME = J.TIME
JOIN POSICAO_JOGADOR P
ON P.JOGADOR = J.CPF;

-- JOSE			PALMEIRAS		(NULL)		SP		GOLEIRO
-- ALFREDO		RIO DE JANEIRO	CHAPECOENSE	SC		ATACANTE
-- NETO			FLORIANOPOLIS	CHAPECOENSE	SC		GOLEIRO
-- REINALDO		SAO PAULO		SANTOS		SP		MEIA
-- ALESSANDRO	BELO HORIZONTE	SANTOS		SP		ATACANTE
-- EDERSON		CAMPINAS		SANTOS		SP		ZAGUEIRO
-- SANTIAGO		IBATE			UNIDOS		(NULL)	ZAGUEIRO


--Q8
SELECT
    *
FROM
    PARTIDA
WHERE TO_DATE(DATA) > TO_DATE(SYSDATE)
AND LOCAL IS NULL;

-- CRUZEIRO	SANTOS		07/12/18	3X2	
-- VASCO	FLAMENGO	03/12/18	0X0	


--Q9
SELECT
    TIME1 AS TIME
FROM
    PARTIDA
WHERE NOT(TO_DATE(DATA) BETWEEN TO_DATE('01-MAR-2018')
AND TO_DATE('30-ABR-2018'))
UNION
SELECT
    TIME2 AS TIME
FROM
    PARTIDA
WHERE NOT(TO_DATE(DATA) BETWEEN TO_DATE('01-MAR-2018')
AND TO_DATE('30-ABR-2018'));

-- CRUZEIRO
-- FLAMENGO
-- INTER
-- PALMEIRAS
-- SANTOS
-- UNIDOS
-- VASCO

--Q10
SELECT
    P.DATA,
    P.PLACAR,
    P.TIME1,
    T1.ESTADO,
    P.TIME2,
    T2.ESTADO
FROM
    PARTIDA P
JOIN TIME T1
ON P.TIME1 = T1.NOME
JOIN TIME T2
ON P.TIME2 = T2.NOME;

-- 02/03/18	1X0	INTER		SP	PALMEIRAS	SP
-- 03/12/18	0X0	VASCO		RJ	FLAMENGO	RJ
-- 10/02/18	2X1	VASCO		RJ	FLAMENGO	RJ
-- 30/04/18	0X0	VASCO		RJ	CHAPECOENSE	SC
-- 01/02/18	4X2	PALMEIRAS	SP	SANTOS		SP
-- 01/07/18	0X2	CRUZEIRO	MG	SANTOS		SP
-- 07/12/18	3X2	CRUZEIRO	MG	SANTOS		SP
-- 01/12/18	0X0	UNIDOS			INTER		SP


--Q11
SELECT
    P.DATA,
    P.PLACAR,
    P.TIME1,
    T1.ESTADO,
    P.TIME2,
    T2.ESTADO,
    J.CLASSICO
FROM
    PARTIDA P
JOIN TIME T1
ON P.TIME1 = T1.NOME
JOIN TIME T2
ON P.TIME2 = T2.NOME
JOIN JOGA J
ON P.TIME1 = J.TIME1
AND P.TIME2 = J.TIME2;
-- 02/03/18	1X0	INTER		SP	PALMEIRAS	SP	N
-- 10/02/18	2X1	VASCO		RJ	FLAMENGO	RJ	S
-- 03/12/18	0X0	VASCO		RJ	FLAMENGO	RJ	S
-- 30/04/18	0X0	VASCO		RJ	CHAPECOENSE	SC	N
-- 07/12/18	3X2	CRUZEIRO	MG	SANTOS		SP	N
-- 01/07/18	0X2	CRUZEIRO	MG	SANTOS		SP	N
-- 01/02/18	4X2	PALMEIRAS	SP	SANTOS		SP	S
-- 01/12/18	0X0	UNIDOS			INTER		SP	


--Q12
SELECT
    COUNT(CLASSICO)
FROM JOGA
JOIN PARTIDA
ON partida.time1 = JOGA.TIME1
AND partida.time2 = JOGA.TIME2
WHERE JOGA.CLASSICO = 'S'
AND EXTRACT(MONTH FROM PARTIDA.DATA) = 2;
-- 2

--Q13
SELECT
    AVG(SALDO_GOLS),
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL
GROUP BY ESTADO
ORDER BY ESTADO;
-- 17	MG
-- 6	RJ
-- 20	SC
-- 15	SP

--Q14
SELECT
    AVG(SALDO_GOLS),
    COUNT(NOME) AS QTD_TIMES,
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL
GROUP BY ESTADO
ORDER BY QTD_TIMES;
-- 17	1	MG
-- 20	1	SC
-- 15	3	SP
-- 6	3	RJ

--Q15 
SELECT
    AVG(SALDO_GOLS),
    COUNT(NOME) AS QTD_TIMES,
    TIPO,
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL
GROUP BY ESTADO, TIPO
ORDER BY ESTADO, TIPO;
-- 17	1	PROFISSIONAL	MG
-- 6	3	PROFISSIONAL	RJ
-- 20	1	PROFISSIONAL	SC
-- 1	1	AMADOR			SP
-- 22	2	PROFISSIONAL	SP


--Q16
SELECT
    AVG(SALDO_GOLS) AS SALDO_GOLS,
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL 
    AND TIPO = 'PROFISSIONAL'
GROUP BY ESTADO
HAVING AVG(SALDO_GOLS) >= 1
ORDER BY ESTADO;
-- 17	MG
-- 6	RJ
-- 20	SC
-- 22	SP

--Q17
SELECT
    AVG(SALDO_GOLS) AS SALDO_GOLS,
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL 
    AND TIPO = 'PROFISSIONAL'
GROUP BY ESTADO
HAVING COUNT(ESTADO) > 1
ORDER BY ESTADO;
-- 6	RJ
-- 22	SP

--Q18
SELECT
    AVG(SALDO_GOLS) AS SALDO_GOLS,
    ESTADO
FROM TIME
WHERE ESTADO IS NOT NULL 
    AND TIPO = 'PROFISSIONAL'
GROUP BY ESTADO
HAVING AVG(SALDO_GOLS) BETWEEN 5 AND 15
AND COUNT(ESTADO) > 1
ORDER BY ESTADO;
-- 6	RJ

--Q19
SELECT
    COUNT(*),
    TIME1,
    TIME2
FROM
    PARTIDA
GROUP BY TIME1, TIME2;
-- 2	CRUZEIRO	SANTOS
-- 1	INTER		PALMEIRAS
-- 1	PALMEIRAS	SANTOS
-- 1	UNIDOS		INTER
-- 1	VASCO		CHAPECOENSE
-- 2	VASCO		FLAMENGO

--Q20
SELECT
    T.NOME,
    T.ESTADO,
    D.NOME
FROM
    TIME T
LEFT JOIN DIRETOR D
ON T.NOME = D.TIME;
-- BOTAFOGO		RJ		(null)
-- CHAPECOENSE	SC		GILSON
-- CRUZEIRO		MG		MANO MENEZES
-- FLAMENGO		RJ		(null)
-- INTER		SP		AUGUSTO
-- PALMEIRAS	SP		ROGER MACHADO
-- SANTOS		SP		JAIR
-- UNIDOS		(null)	CAMARGO
-- VASCO		RJ		ZE RICARDO

--Q21 (VERIFICAR SE COBRE CASO DE TIME QUE NAO JOGOU)
SELECT
    T.NOME,
    T.ESTADO,
    P.TIME2 AS ADVERSARIO,
    P.DATA,
    J.CLASSICO
FROM TIME T
JOIN PARTIDA P
ON T.NOME = P.TIME1
JOIN JOGA J
ON P.TIME1 = J.TIME1
AND P.TIME2 = J.TIME2
ORDER BY NOME, DATA;
-- CRUZEIRO		MG	SANTOS		01/07/18	N
-- CRUZEIRO		MG	SANTOS		07/12/18	N
-- INTER		SP	PALMEIRAS	02/03/18	N
-- PALMEIRAS	SP	SANTOS		01/02/18	S
-- UNIDOS			INTER		01/12/18	
-- VASCO		RJ	FLAMENGO	10/02/18	S
-- VASCO		RJ	CHAPECOENSE	30/04/18	N
-- VASCO		RJ	FLAMENGO	03/12/18	S

--EX4
--a
INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
VALUES ('PALMEIRAS', NULL, 'S');
-- Erro a partir da linha : 1 no comando -
-- INSERT INTO JOGA (TIME1, TIME2, CLASSICO) VALUES ('PALMEIRAS', NULL, 'S')
-- Relatório de erros -
-- ORA-01400: não é possível inserir NULL em ("H8936972"."JOGA"."TIME2")

--b
INSERT INTO PARTIDA (TIME1, TIME2, DATA, PLACAR, LOCAL)
VALUES ('PALMEIRAS', 'SANTOS', TO_DATE('2018/04/11', 'YYYY/MM/DD'), NULL, 'SÃO CARLOS');
-- 1 linha inserido.
-- PALMEIRAS	SANTOS	11/04/18	(NULL)	SÃO CARLOS

INSERT INTO PARTIDA (TIME1, TIME2, DATA, LOCAL)
VALUES ('PALMEIRAS', 'SANTOS', TO_DATE('2018/04/12', 'YYYY/MM/DD'),'SÃO CARLOS');
-- 1 linha inserido.
-- PALMEIRAS	SANTOS	12/04/18	0X0		SÃO CARLOS

--c.i
UPDATE TIME SET NOME = 'CHAPE' 
WHERE NOME = 'CHAPECOENSE';
-- Relatório de erros -
-- ORA-02292: restrição de integridade (H8936972.FK_TIME2) violada - registro filho localizado

-- O nome não é atualizado porque nome é chave primaria e não existe uma condição "ON UPDATE"

--c.ii
UPDATE TIME SET ESTADO = 'MG' 
WHERE NOME = 'CHAPECOENSE';
-- 1 linha atualizado.
