SELECT TIME.ID, TIME.ESPORTE, TIME.SEXO, JOGADOR.NOME, PARTICIPACAO.POSICAO, PARTICIPACAO.NUMERO
FROM PARTICIPACAO
INNER JOIN TIME ON PARTICIPACAO.TIME = TIME.ID
INNER JOIN JOGADOR ON JOGADOR.CPF = PARTICIPACAO.JOGADOR
WHERE TIME.SIGLA = 'CAASO' AND date_part('year', CURRENT_DATE) = date_part('year', ano)
ORDER BY TIME.ESPORTE;
